# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FenetrePersonnalisable.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_FenetrePersonnalisable(object):
    def setupUi(self, FenetrePersonnalisable):
        FenetrePersonnalisable.setObjectName("FenetrePersonnalisable")
        FenetrePersonnalisable.resize(733, 549)
        FenetrePersonnalisable.setStyleSheet("background: white\n"
"")
        self.centralwidget = QtWidgets.QWidget(FenetrePersonnalisable)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelIcon = QtWidgets.QLabel(self.centralwidget)
        self.labelIcon.setMaximumSize(QtCore.QSize(32, 32))
        self.labelIcon.setText("")
        self.labelIcon.setPixmap(QtGui.QPixmap("Images/list.png"))
        self.labelIcon.setObjectName("labelIcon")
        self.horizontalLayout.addWidget(self.labelIcon)
        self.labelTitre = QtWidgets.QLabel(self.centralwidget)
        self.labelTitre.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitre.setFont(font)
        self.labelTitre.setObjectName("labelTitre")
        self.horizontalLayout.addWidget(self.labelTitre)
        spacerItem = QtWidgets.QSpacerItem(27, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelInstructions_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelInstructions_2.setFont(font)
        self.labelInstructions_2.setObjectName("labelInstructions_2")
        self.horizontalLayout_6.addWidget(self.labelInstructions_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBoxAjoutEquipement = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxAjoutEquipement.sizePolicy().hasHeightForWidth())
        self.checkBoxAjoutEquipement.setSizePolicy(sizePolicy)
        self.checkBoxAjoutEquipement.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxAjoutEquipement.setFont(font)
        self.checkBoxAjoutEquipement.setText("")
        self.checkBoxAjoutEquipement.setTristate(False)
        self.checkBoxAjoutEquipement.setObjectName("checkBoxAjoutEquipement")
        self.horizontalLayout_8.addWidget(self.checkBoxAjoutEquipement)
        self.labelIconAjoutEquipement = QtWidgets.QLabel(self.centralwidget)
        self.labelIconAjoutEquipement.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelIconAjoutEquipement.setText("")
        self.labelIconAjoutEquipement.setPixmap(QtGui.QPixmap("Images/add1.png"))
        self.labelIconAjoutEquipement.setObjectName("labelIconAjoutEquipement")
        self.horizontalLayout_8.addWidget(self.labelIconAjoutEquipement)
        self.labelAjoutEquipement = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAjoutEquipement.setFont(font)
        self.labelAjoutEquipement.setObjectName("labelAjoutEquipement")
        self.horizontalLayout_8.addWidget(self.labelAjoutEquipement)
        self.checkBoxModificationEquipement = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxModificationEquipement.sizePolicy().hasHeightForWidth())
        self.checkBoxModificationEquipement.setSizePolicy(sizePolicy)
        self.checkBoxModificationEquipement.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxModificationEquipement.setFont(font)
        self.checkBoxModificationEquipement.setText("")
        self.checkBoxModificationEquipement.setObjectName("checkBoxModificationEquipement")
        self.horizontalLayout_8.addWidget(self.checkBoxModificationEquipement)
        self.labelIconModificationEquipement = QtWidgets.QLabel(self.centralwidget)
        self.labelIconModificationEquipement.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelIconModificationEquipement.setText("")
        self.labelIconModificationEquipement.setPixmap(QtGui.QPixmap("Images/pencil-edit-button_Hatim.png"))
        self.labelIconModificationEquipement.setObjectName("labelIconModificationEquipement")
        self.horizontalLayout_8.addWidget(self.labelIconModificationEquipement)
        self.labelModificationEquipement = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelModificationEquipement.setFont(font)
        self.labelModificationEquipement.setObjectName("labelModificationEquipement")
        self.horizontalLayout_8.addWidget(self.labelModificationEquipement)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.checkBoxRechercheEquipement = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxRechercheEquipement.sizePolicy().hasHeightForWidth())
        self.checkBoxRechercheEquipement.setSizePolicy(sizePolicy)
        self.checkBoxRechercheEquipement.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxRechercheEquipement.setFont(font)
        self.checkBoxRechercheEquipement.setText("")
        self.checkBoxRechercheEquipement.setObjectName("checkBoxRechercheEquipement")
        self.horizontalLayout_9.addWidget(self.checkBoxRechercheEquipement)
        self.labelIconRechercheEquipment = QtWidgets.QLabel(self.centralwidget)
        self.labelIconRechercheEquipment.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelIconRechercheEquipment.setText("")
        self.labelIconRechercheEquipment.setPixmap(QtGui.QPixmap("Images/magnifier.png"))
        self.labelIconRechercheEquipment.setObjectName("labelIconRechercheEquipment")
        self.horizontalLayout_9.addWidget(self.labelIconRechercheEquipment)
        self.labelRechercheEquipement = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelRechercheEquipement.setFont(font)
        self.labelRechercheEquipement.setObjectName("labelRechercheEquipement")
        self.horizontalLayout_9.addWidget(self.labelRechercheEquipement)
        self.checkBoxAjoutPiece = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxAjoutPiece.sizePolicy().hasHeightForWidth())
        self.checkBoxAjoutPiece.setSizePolicy(sizePolicy)
        self.checkBoxAjoutPiece.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxAjoutPiece.setFont(font)
        self.checkBoxAjoutPiece.setText("")
        self.checkBoxAjoutPiece.setObjectName("checkBoxAjoutPiece")
        self.horizontalLayout_9.addWidget(self.checkBoxAjoutPiece)
        self.labelIconAjoutPiece = QtWidgets.QLabel(self.centralwidget)
        self.labelIconAjoutPiece.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelIconAjoutPiece.setText("")
        self.labelIconAjoutPiece.setPixmap(QtGui.QPixmap("Images/screwdriver-and-wrench-crossed (3).png"))
        self.labelIconAjoutPiece.setObjectName("labelIconAjoutPiece")
        self.horizontalLayout_9.addWidget(self.labelIconAjoutPiece)
        self.labelAjoutPiece = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAjoutPiece.setFont(font)
        self.labelAjoutPiece.setObjectName("labelAjoutPiece")
        self.horizontalLayout_9.addWidget(self.labelAjoutPiece)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.checkBoxAjoutBonTravail = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxAjoutBonTravail.sizePolicy().hasHeightForWidth())
        self.checkBoxAjoutBonTravail.setSizePolicy(sizePolicy)
        self.checkBoxAjoutBonTravail.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxAjoutBonTravail.setFont(font)
        self.checkBoxAjoutBonTravail.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxAjoutBonTravail.setText("")
        self.checkBoxAjoutBonTravail.setObjectName("checkBoxAjoutBonTravail")
        self.horizontalLayout_10.addWidget(self.checkBoxAjoutBonTravail)
        self.labelIconAjoutBonTravail = QtWidgets.QLabel(self.centralwidget)
        self.labelIconAjoutBonTravail.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelIconAjoutBonTravail.setText("")
        self.labelIconAjoutBonTravail.setPixmap(QtGui.QPixmap("Images/plus.png"))
        self.labelIconAjoutBonTravail.setObjectName("labelIconAjoutBonTravail")
        self.horizontalLayout_10.addWidget(self.labelIconAjoutBonTravail)
        self.labelAjoutBonTravail = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAjoutBonTravail.setFont(font)
        self.labelAjoutBonTravail.setObjectName("labelAjoutBonTravail")
        self.horizontalLayout_10.addWidget(self.labelAjoutBonTravail)
        self.checkBoxRechercheBonTravail = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxRechercheBonTravail.sizePolicy().hasHeightForWidth())
        self.checkBoxRechercheBonTravail.setSizePolicy(sizePolicy)
        self.checkBoxRechercheBonTravail.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxRechercheBonTravail.setFont(font)
        self.checkBoxRechercheBonTravail.setText("")
        self.checkBoxRechercheBonTravail.setObjectName("checkBoxRechercheBonTravail")
        self.horizontalLayout_10.addWidget(self.checkBoxRechercheBonTravail)
        self.labelRechercheBonTravail = QtWidgets.QLabel(self.centralwidget)
        self.labelRechercheBonTravail.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelRechercheBonTravail.setText("")
        self.labelRechercheBonTravail.setPixmap(QtGui.QPixmap("Images/magnifier (1).png"))
        self.labelRechercheBonTravail.setObjectName("labelRechercheBonTravail")
        self.horizontalLayout_10.addWidget(self.labelRechercheBonTravail)
        self.labelRechercheBonTravail_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelRechercheBonTravail_2.setFont(font)
        self.labelRechercheBonTravail_2.setObjectName("labelRechercheBonTravail_2")
        self.horizontalLayout_10.addWidget(self.labelRechercheBonTravail_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.checkBoxImprimer = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxImprimer.sizePolicy().hasHeightForWidth())
        self.checkBoxImprimer.setSizePolicy(sizePolicy)
        self.checkBoxImprimer.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxImprimer.setFont(font)
        self.checkBoxImprimer.setText("")
        self.checkBoxImprimer.setObjectName("checkBoxImprimer")
        self.horizontalLayout_11.addWidget(self.checkBoxImprimer)
        self.labelIconImprimer = QtWidgets.QLabel(self.centralwidget)
        self.labelIconImprimer.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelIconImprimer.setText("")
        self.labelIconImprimer.setPixmap(QtGui.QPixmap("Images/printer- (3).png"))
        self.labelIconImprimer.setObjectName("labelIconImprimer")
        self.horizontalLayout_11.addWidget(self.labelIconImprimer)
        self.labelImprimer = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelImprimer.setFont(font)
        self.labelImprimer.setObjectName("labelImprimer")
        self.horizontalLayout_11.addWidget(self.labelImprimer)
        self.checkBoxStastistiques = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxStastistiques.sizePolicy().hasHeightForWidth())
        self.checkBoxStastistiques.setSizePolicy(sizePolicy)
        self.checkBoxStastistiques.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxStastistiques.setFont(font)
        self.checkBoxStastistiques.setText("")
        self.checkBoxStastistiques.setObjectName("checkBoxStastistiques")
        self.horizontalLayout_11.addWidget(self.checkBoxStastistiques)
        self.labelStatistiques = QtWidgets.QLabel(self.centralwidget)
        self.labelStatistiques.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelStatistiques.setText("")
        self.labelStatistiques.setPixmap(QtGui.QPixmap("Images/pie-chart (1).png"))
        self.labelStatistiques.setObjectName("labelStatistiques")
        self.horizontalLayout_11.addWidget(self.labelStatistiques)
        self.labelStatistique = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStatistique.setFont(font)
        self.labelStatistique.setObjectName("labelStatistique")
        self.horizontalLayout_11.addWidget(self.labelStatistique)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.checkBoxSupportTechnique = QtWidgets.QCheckBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxSupportTechnique.sizePolicy().hasHeightForWidth())
        self.checkBoxSupportTechnique.setSizePolicy(sizePolicy)
        self.checkBoxSupportTechnique.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxSupportTechnique.setFont(font)
        self.checkBoxSupportTechnique.setText("")
        self.checkBoxSupportTechnique.setObjectName("checkBoxSupportTechnique")
        self.horizontalLayout_12.addWidget(self.checkBoxSupportTechnique)
        self.labelIconSupportTechnique = QtWidgets.QLabel(self.centralwidget)
        self.labelIconSupportTechnique.setMaximumSize(QtCore.QSize(32, 32))
        self.labelIconSupportTechnique.setText("")
        self.labelIconSupportTechnique.setPixmap(QtGui.QPixmap("Images/PC2.png"))
        self.labelIconSupportTechnique.setScaledContents(True)
        self.labelIconSupportTechnique.setObjectName("labelIconSupportTechnique")
        self.horizontalLayout_12.addWidget(self.labelIconSupportTechnique)
        self.labelSupportTechnique = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelSupportTechnique.setFont(font)
        self.labelSupportTechnique.setObjectName("labelSupportTechnique")
        self.horizontalLayout_12.addWidget(self.labelSupportTechnique)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        FenetrePersonnalisable.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(FenetrePersonnalisable)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 733, 26))
        self.menubar.setObjectName("menubar")
        FenetrePersonnalisable.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(FenetrePersonnalisable)
        self.statusbar.setObjectName("statusbar")
        FenetrePersonnalisable.setStatusBar(self.statusbar)

        self.retranslateUi(FenetrePersonnalisable)
        QtCore.QMetaObject.connectSlotsByName(FenetrePersonnalisable)

    def retranslateUi(self, FenetrePersonnalisable):
        _translate = QtCore.QCoreApplication.translate
        FenetrePersonnalisable.setWindowTitle(_translate("FenetrePersonnalisable", "MainWindow"))
        self.labelTitre.setText(_translate("FenetrePersonnalisable", "Fenêtre personnalisable"))
        self.labelInstructions_2.setText(_translate("FenetrePersonnalisable", "Cochez les onglets à montrer à l\'utilisateur"))
        self.labelAjoutEquipement.setText(_translate("FenetrePersonnalisable", "Ajouter un équipement"))
        self.labelModificationEquipement.setText(_translate("FenetrePersonnalisable", "Modifier ou consulter un équipement"))
        self.labelRechercheEquipement.setText(_translate("FenetrePersonnalisable", "Rechercher un équipement"))
        self.labelAjoutPiece.setText(_translate("FenetrePersonnalisable", "Ajouter une pièce"))
        self.labelAjoutBonTravail.setText(_translate("FenetrePersonnalisable", "Ajouter un bon de travail"))
        self.labelRechercheBonTravail_2.setText(_translate("FenetrePersonnalisable", "Rechercher un bon de travail"))
        self.labelImprimer.setText(_translate("FenetrePersonnalisable", "Imprimer tout l\'inventaire"))
        self.labelStatistique.setText(_translate("FenetrePersonnalisable", "Voir les statistiques"))
        self.labelSupportTechnique.setText(_translate("FenetrePersonnalisable", "Support technique"))

