# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FenetresEnUI/FenetrePersonnalisable1.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from win32api import GetSystemMetrics
class Ui_FenetrePersonnalisable(object):
    def setupUi(self, FenetrePersonnalisable):
        FenetrePersonnalisable.setObjectName("FenetrePersonnalisable")
        width = GetSystemMetrics(0)
        heigth = GetSystemMetrics(1)
        facteur_grandissement_width = 0.9
        facteur_grandissement_heigth = 0.7
        FenetrePersonnalisable.resize(width * facteur_grandissement_width, heigth * facteur_grandissement_heigth)
        #FenetrePersonnalisable.resize(979, 598)
        FenetrePersonnalisable.setStyleSheet("background: white;")
        self.gridLayout = QtWidgets.QGridLayout(FenetrePersonnalisable)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout.setSpacing(7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.labelIcon = QtWidgets.QLabel(FenetrePersonnalisable)
        self.labelIcon.setMaximumSize(QtCore.QSize(32, 32))
        self.labelIcon.setText("")
        self.labelIcon.setPixmap(QtGui.QPixmap("Images/list.png"))
        self.labelIcon.setObjectName("labelIcon")
        self.horizontalLayout.addWidget(self.labelIcon)
        self.labelTitre = QtWidgets.QLabel(FenetrePersonnalisable)
        self.labelTitre.setMaximumSize(QtCore.QSize(16777215, 32))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.labelTitre.setFont(font)
        self.labelTitre.setObjectName("labelTitre")
        self.horizontalLayout.addWidget(self.labelTitre)
        spacerItem = QtWidgets.QSpacerItem(27, 19, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelInstructions_2 = QtWidgets.QLabel(FenetrePersonnalisable)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelInstructions_2.setFont(font)
        self.labelInstructions_2.setObjectName("labelInstructions_2")
        self.horizontalLayout_6.addWidget(self.labelInstructions_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBoxAjoutEquipement = QtWidgets.QCheckBox(FenetrePersonnalisable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxAjoutEquipement.sizePolicy().hasHeightForWidth())
        self.checkBoxAjoutEquipement.setSizePolicy(sizePolicy)
        self.checkBoxAjoutEquipement.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxAjoutEquipement.setFont(font)
        self.checkBoxAjoutEquipement.setStyleSheet("")
        self.checkBoxAjoutEquipement.setText("")
        self.checkBoxAjoutEquipement.setTristate(False)
        self.checkBoxAjoutEquipement.setObjectName("checkBoxAjoutEquipement")
        self.horizontalLayout_3.addWidget(self.checkBoxAjoutEquipement)
        self.labelIconAjoutEquipement = QtWidgets.QLabel(FenetrePersonnalisable)
        self.labelIconAjoutEquipement.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelIconAjoutEquipement.setText("")
        self.labelIconAjoutEquipement.setPixmap(QtGui.QPixmap("Images/add1.png"))
        self.labelIconAjoutEquipement.setAlignment(QtCore.Qt.AlignCenter)
        self.labelIconAjoutEquipement.setObjectName("labelIconAjoutEquipement")
        self.horizontalLayout_3.addWidget(self.labelIconAjoutEquipement)
        self.labelAjoutEquipement = QtWidgets.QLabel(FenetrePersonnalisable)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAjoutEquipement.setFont(font)
        self.labelAjoutEquipement.setObjectName("labelAjoutEquipement")
        self.horizontalLayout_3.addWidget(self.labelAjoutEquipement)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.checkBoxRechercheEquipement = QtWidgets.QCheckBox(FenetrePersonnalisable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxRechercheEquipement.sizePolicy().hasHeightForWidth())
        self.checkBoxRechercheEquipement.setSizePolicy(sizePolicy)
        self.checkBoxRechercheEquipement.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxRechercheEquipement.setFont(font)
        self.checkBoxRechercheEquipement.setText("")
        self.checkBoxRechercheEquipement.setObjectName("checkBoxRechercheEquipement")
        self.horizontalLayout_8.addWidget(self.checkBoxRechercheEquipement)
        self.labelIconRechercheEquipment = QtWidgets.QLabel(FenetrePersonnalisable)
        self.labelIconRechercheEquipment.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelIconRechercheEquipment.setText("")
        self.labelIconRechercheEquipment.setPixmap(QtGui.QPixmap("Images/magnifier.png"))
        self.labelIconRechercheEquipment.setObjectName("labelIconRechercheEquipment")
        self.horizontalLayout_8.addWidget(self.labelIconRechercheEquipment)
        self.labelRechercheEquipement = QtWidgets.QLabel(FenetrePersonnalisable)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelRechercheEquipement.setFont(font)
        self.labelRechercheEquipement.setObjectName("labelRechercheEquipement")
        self.horizontalLayout_8.addWidget(self.labelRechercheEquipement)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.checkBoxAjoutBonTravail = QtWidgets.QCheckBox(FenetrePersonnalisable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxAjoutBonTravail.sizePolicy().hasHeightForWidth())
        self.checkBoxAjoutBonTravail.setSizePolicy(sizePolicy)
        self.checkBoxAjoutBonTravail.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxAjoutBonTravail.setFont(font)
        self.checkBoxAjoutBonTravail.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.checkBoxAjoutBonTravail.setText("")
        self.checkBoxAjoutBonTravail.setObjectName("checkBoxAjoutBonTravail")
        self.horizontalLayout_13.addWidget(self.checkBoxAjoutBonTravail)
        self.labelIconAjoutBonTravail = QtWidgets.QLabel(FenetrePersonnalisable)
        self.labelIconAjoutBonTravail.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelIconAjoutBonTravail.setText("")
        self.labelIconAjoutBonTravail.setPixmap(QtGui.QPixmap("Images/plus.png"))
        self.labelIconAjoutBonTravail.setObjectName("labelIconAjoutBonTravail")
        self.horizontalLayout_13.addWidget(self.labelIconAjoutBonTravail)
        self.labelAjoutBonTravail = QtWidgets.QLabel(FenetrePersonnalisable)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAjoutBonTravail.setFont(font)
        self.labelAjoutBonTravail.setObjectName("labelAjoutBonTravail")
        self.horizontalLayout_13.addWidget(self.labelAjoutBonTravail)
        self.verticalLayout_4.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.checkBoxImprimer = QtWidgets.QCheckBox(FenetrePersonnalisable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxImprimer.sizePolicy().hasHeightForWidth())
        self.checkBoxImprimer.setSizePolicy(sizePolicy)
        self.checkBoxImprimer.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxImprimer.setFont(font)
        self.checkBoxImprimer.setText("")
        self.checkBoxImprimer.setObjectName("checkBoxImprimer")
        self.horizontalLayout_15.addWidget(self.checkBoxImprimer)
        self.labelIconImprimer = QtWidgets.QLabel(FenetrePersonnalisable)
        self.labelIconImprimer.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelIconImprimer.setText("")
        self.labelIconImprimer.setPixmap(QtGui.QPixmap("Images/printer- (3).png"))
        self.labelIconImprimer.setObjectName("labelIconImprimer")
        self.horizontalLayout_15.addWidget(self.labelIconImprimer)
        self.labelImprimer = QtWidgets.QLabel(FenetrePersonnalisable)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelImprimer.setFont(font)
        self.labelImprimer.setObjectName("labelImprimer")
        self.horizontalLayout_15.addWidget(self.labelImprimer)
        self.verticalLayout_4.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.checkBoxSupportTechnique = QtWidgets.QCheckBox(FenetrePersonnalisable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxSupportTechnique.sizePolicy().hasHeightForWidth())
        self.checkBoxSupportTechnique.setSizePolicy(sizePolicy)
        self.checkBoxSupportTechnique.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxSupportTechnique.setFont(font)
        self.checkBoxSupportTechnique.setText("")
        self.checkBoxSupportTechnique.setObjectName("checkBoxSupportTechnique")
        self.horizontalLayout_4.addWidget(self.checkBoxSupportTechnique)
        self.labelIconSupportTechnique = QtWidgets.QLabel(FenetrePersonnalisable)
        self.labelIconSupportTechnique.setMaximumSize(QtCore.QSize(32, 32))
        self.labelIconSupportTechnique.setText("")
        self.labelIconSupportTechnique.setPixmap(QtGui.QPixmap("Images/PC2.png"))
        self.labelIconSupportTechnique.setScaledContents(True)
        self.labelIconSupportTechnique.setObjectName("labelIconSupportTechnique")
        self.horizontalLayout_4.addWidget(self.labelIconSupportTechnique)
        self.labelSupportTechnique = QtWidgets.QLabel(FenetrePersonnalisable)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelSupportTechnique.setFont(font)
        self.labelSupportTechnique.setObjectName("labelSupportTechnique")
        self.horizontalLayout_4.addWidget(self.labelSupportTechnique)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.checkBoxModificationEquipement = QtWidgets.QCheckBox(FenetrePersonnalisable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxModificationEquipement.sizePolicy().hasHeightForWidth())
        self.checkBoxModificationEquipement.setSizePolicy(sizePolicy)
        self.checkBoxModificationEquipement.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxModificationEquipement.setFont(font)
        self.checkBoxModificationEquipement.setText("")
        self.checkBoxModificationEquipement.setObjectName("checkBoxModificationEquipement")
        self.horizontalLayout_7.addWidget(self.checkBoxModificationEquipement)
        self.labelIconModificationEquipement = QtWidgets.QLabel(FenetrePersonnalisable)
        self.labelIconModificationEquipement.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelIconModificationEquipement.setText("")
        self.labelIconModificationEquipement.setPixmap(QtGui.QPixmap("Images/pencil-edit-button_Hatim.png"))
        self.labelIconModificationEquipement.setObjectName("labelIconModificationEquipement")
        self.horizontalLayout_7.addWidget(self.labelIconModificationEquipement)
        self.labelModificationEquipement = QtWidgets.QLabel(FenetrePersonnalisable)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelModificationEquipement.setFont(font)
        self.labelModificationEquipement.setObjectName("labelModificationEquipement")
        self.horizontalLayout_7.addWidget(self.labelModificationEquipement)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBoxAjoutPiece = QtWidgets.QCheckBox(FenetrePersonnalisable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxAjoutPiece.sizePolicy().hasHeightForWidth())
        self.checkBoxAjoutPiece.setSizePolicy(sizePolicy)
        self.checkBoxAjoutPiece.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxAjoutPiece.setFont(font)
        self.checkBoxAjoutPiece.setText("")
        self.checkBoxAjoutPiece.setObjectName("checkBoxAjoutPiece")
        self.horizontalLayout_5.addWidget(self.checkBoxAjoutPiece)
        self.labelIconAjoutPiece = QtWidgets.QLabel(FenetrePersonnalisable)
        self.labelIconAjoutPiece.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelIconAjoutPiece.setText("")
        self.labelIconAjoutPiece.setPixmap(QtGui.QPixmap("Images/screwdriver-and-wrench-crossed (3).png"))
        self.labelIconAjoutPiece.setObjectName("labelIconAjoutPiece")
        self.horizontalLayout_5.addWidget(self.labelIconAjoutPiece)
        self.labelAjoutPiece = QtWidgets.QLabel(FenetrePersonnalisable)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelAjoutPiece.setFont(font)
        self.labelAjoutPiece.setObjectName("labelAjoutPiece")
        self.horizontalLayout_5.addWidget(self.labelAjoutPiece)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.checkBoxRechercheBonTravail = QtWidgets.QCheckBox(FenetrePersonnalisable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxRechercheBonTravail.sizePolicy().hasHeightForWidth())
        self.checkBoxRechercheBonTravail.setSizePolicy(sizePolicy)
        self.checkBoxRechercheBonTravail.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxRechercheBonTravail.setFont(font)
        self.checkBoxRechercheBonTravail.setText("")
        self.checkBoxRechercheBonTravail.setObjectName("checkBoxRechercheBonTravail")
        self.horizontalLayout_14.addWidget(self.checkBoxRechercheBonTravail)
        self.labelRechercheBonTravail = QtWidgets.QLabel(FenetrePersonnalisable)
        self.labelRechercheBonTravail.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelRechercheBonTravail.setText("")
        self.labelRechercheBonTravail.setPixmap(QtGui.QPixmap("Images/magnifier (1).png"))
        self.labelRechercheBonTravail.setObjectName("labelRechercheBonTravail")
        self.horizontalLayout_14.addWidget(self.labelRechercheBonTravail)
        self.labelRechercheBonTravail_2 = QtWidgets.QLabel(FenetrePersonnalisable)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelRechercheBonTravail_2.setFont(font)
        self.labelRechercheBonTravail_2.setObjectName("labelRechercheBonTravail_2")
        self.horizontalLayout_14.addWidget(self.labelRechercheBonTravail_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.checkBoxStastistiques = QtWidgets.QCheckBox(FenetrePersonnalisable)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBoxStastistiques.sizePolicy().hasHeightForWidth())
        self.checkBoxStastistiques.setSizePolicy(sizePolicy)
        self.checkBoxStastistiques.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBoxStastistiques.setFont(font)
        self.checkBoxStastistiques.setText("")
        self.checkBoxStastistiques.setObjectName("checkBoxStastistiques")
        self.horizontalLayout_16.addWidget(self.checkBoxStastistiques)
        self.labelStatistiques = QtWidgets.QLabel(FenetrePersonnalisable)
        self.labelStatistiques.setMaximumSize(QtCore.QSize(32, 16777215))
        self.labelStatistiques.setText("")
        self.labelStatistiques.setPixmap(QtGui.QPixmap("Images/pie-chart (1).png"))
        self.labelStatistiques.setObjectName("labelStatistiques")
        self.horizontalLayout_16.addWidget(self.labelStatistiques)
        self.labelStatistique = QtWidgets.QLabel(FenetrePersonnalisable)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelStatistique.setFont(font)
        self.labelStatistique.setObjectName("labelStatistique")
        self.horizontalLayout_16.addWidget(self.labelStatistique)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.verticalLayout_3.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.boutonEnregistrer = QtWidgets.QPushButton(FenetrePersonnalisable)
        self.boutonEnregistrer.setStyleSheet("QPushButton {\n"
"color: black;\n"
"background-color:rgb(245, 245, 245);\n"
"border-width: 1px;\n"
"border-color: grey;\n"
"border-style: solid;\n"
"border-radius: 4px;\n"
"padding: 3px;\n"
"font: bold 12px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"min-width: 80px;\n"
"max-width:220px;\n"
"min-height: 30px;\n"
"max-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #edf2f8, stop: 1 #c8d9ea);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(193, 213, 243);\n"
"}\n"
"")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/save (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.boutonEnregistrer.setIcon(icon)
        self.boutonEnregistrer.setObjectName("boutonEnregistrer")
        self.horizontalLayout_10.addWidget(self.boutonEnregistrer)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 1, 1, 1)

        self.retranslateUi(FenetrePersonnalisable)
        QtCore.QMetaObject.connectSlotsByName(FenetrePersonnalisable)

    def retranslateUi(self, FenetrePersonnalisable):
        _translate = QtCore.QCoreApplication.translate
        FenetrePersonnalisable.setWindowTitle(_translate("FenetrePersonnalisable", "Form"))
        self.labelTitre.setText(_translate("FenetrePersonnalisable", "Fenêtre personnalisable"))
        self.labelInstructions_2.setText(_translate("FenetrePersonnalisable", "Cochez les onglets à montrer à l\'utilisateur"))
        self.labelAjoutEquipement.setText(_translate("FenetrePersonnalisable", "Ajouter un équipement"))
        self.labelRechercheEquipement.setText(_translate("FenetrePersonnalisable", "Rechercher un équipement"))
        self.labelAjoutBonTravail.setText(_translate("FenetrePersonnalisable", "Ajouter un bon de travail"))
        self.labelImprimer.setText(_translate("FenetrePersonnalisable", "Imprimer tout l\'inventaire"))
        self.labelSupportTechnique.setText(_translate("FenetrePersonnalisable", "Support technique"))
        self.labelModificationEquipement.setText(_translate("FenetrePersonnalisable", "Modifier ou consulter un équipement"))
        self.labelAjoutPiece.setText(_translate("FenetrePersonnalisable", "Ajouter une pièce"))
        self.labelRechercheBonTravail_2.setText(_translate("FenetrePersonnalisable", "Rechercher un bon de travail"))
        self.labelStatistique.setText(_translate("FenetrePersonnalisable", "Voir les statistiques"))
        self.boutonEnregistrer.setText(_translate("FenetrePersonnalisable", "Enregistrer"))
