# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ModificationEquipement.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ModificationEquipement(object):
    def setupUi(self, ModificationEquipement):
        ModificationEquipement.setObjectName("ModificationEquipement")
        ModificationEquipement.resize(958, 800)
        ModificationEquipement.setMinimumSize(QtCore.QSize(0, 800))
        ModificationEquipement.setMaximumSize(QtCore.QSize(11111111, 1111111))
        ModificationEquipement.setStyleSheet("QWidget{\n"
"\n"
"background: white;\n"
"}\n"
"\n"
"QLineEdit {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 1px solid gray;\n"
"border-radius: 4px;\n"
"background:rgb(247,247,247);\n"
"\n"
"}\n"
"\n"
"QDateEdit {\n"
"max-width: 105px\n"
"}\n"
"\n"
"QPushButton {\n"
"color: black;\n"
"background-color: rgb(240, 240, 240);\n"
"border-width: 1px;\n"
"border-color: grey;\n"
"border-style: solid;\n"
"border-radius: 4px;\n"
"padding: 3px;\n"
"font: bold 16px;\n"
"padding-left: 5px;\n"
"padding-right: 5px;\n"
"min-width: 130px;\n"
"max-width:150px;\n"
"min-height: 30px;\n"
"max-height: 30px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #edf2f8, stop: 1 #c8d9ea);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"background-color: rgb(193, 213, 243);\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"QComboBox\n"
"{\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 1px solid gray;\n"
"border-radius: 4px;\n"
"background:rgb(247,247,247);\n"
"}\n"
"\n"
"QDateEdit\n"
"{\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 1px solid gray;\n"
"border-radius: 4px;\n"
"background:rgb(247,247,247);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(ModificationEquipement)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.layoutTitreLables = QtWidgets.QVBoxLayout()
        self.layoutTitreLables.setObjectName("layoutTitreLables")
        self.label_34 = QtWidgets.QLabel(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("background: white;")
        self.label_34.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_34.setObjectName("label_34")
        self.layoutTitreLables.addWidget(self.label_34)
        self.label_37 = QtWidgets.QLabel(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("background: white;")
        self.label_37.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_37.setObjectName("label_37")
        self.layoutTitreLables.addWidget(self.label_37)
        self.label_36 = QtWidgets.QLabel(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("background: white;")
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.layoutTitreLables.addWidget(self.label_36)
        self.label_35 = QtWidgets.QLabel(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet("background: white;")
        self.label_35.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_35.setObjectName("label_35")
        self.layoutTitreLables.addWidget(self.label_35)
        self.label_30 = QtWidgets.QLabel(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setStyleSheet("background: white;")
        self.label_30.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_30.setObjectName("label_30")
        self.layoutTitreLables.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("background: white;")
        self.label_31.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_31.setObjectName("label_31")
        self.layoutTitreLables.addWidget(self.label_31)
        self.label_33 = QtWidgets.QLabel(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet("background: white;")
        self.label_33.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_33.setObjectName("label_33")
        self.layoutTitreLables.addWidget(self.label_33)
        self.label_29 = QtWidgets.QLabel(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setStyleSheet("background: white;")
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.layoutTitreLables.addWidget(self.label_29)
        self.label_27 = QtWidgets.QLabel(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("background: white;")
        self.label_27.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_27.setObjectName("label_27")
        self.layoutTitreLables.addWidget(self.label_27)
        self.label_26 = QtWidgets.QLabel(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("background: white;")
        self.label_26.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_26.setObjectName("label_26")
        self.layoutTitreLables.addWidget(self.label_26)
        self.label_2 = QtWidgets.QLabel(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.layoutTitreLables.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.layoutTitreLables)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.layoutChamps_2 = QtWidgets.QVBoxLayout()
        self.layoutChamps_2.setObjectName("layoutChamps_2")
        self.labelId_2 = QtWidgets.QLabel(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelId_2.setFont(font)
        self.labelId_2.setStyleSheet("QLabel\n"
"\n"
"{\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 1px solid gray;\n"
"border-radius: 4px;\n"
"background:rgb(247,247,247);\n"
"}\n"
"")
        self.labelId_2.setText("")
        self.labelId_2.setObjectName("labelId_2")
        self.layoutChamps_2.addWidget(self.labelId_2)
        self.comboBoxCategorie_2 = QtWidgets.QComboBox(ModificationEquipement)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.comboBoxCategorie_2.setFont(font)
        self.comboBoxCategorie_2.setMaxCount(2147483645)
        self.comboBoxCategorie_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBoxCategorie_2.setObjectName("comboBoxCategorie_2")
        self.comboBoxCategorie_2.addItem("")
        self.comboBoxCategorie_2.addItem("")
        self.comboBoxCategorie_2.addItem("")
        self.layoutChamps_2.addWidget(self.comboBoxCategorie_2)
        self.lineEditMarque_2 = QtWidgets.QLineEdit(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditMarque_2.setFont(font)
        self.lineEditMarque_2.setObjectName("lineEditMarque_2")
        self.layoutChamps_2.addWidget(self.lineEditMarque_2)
        self.lineEditModele_2 = QtWidgets.QLineEdit(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditModele_2.setFont(font)
        self.lineEditModele_2.setObjectName("lineEditModele_2")
        self.layoutChamps_2.addWidget(self.lineEditModele_2)
        self.lineEditNoDeSerie_2 = QtWidgets.QLineEdit(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditNoDeSerie_2.setFont(font)
        self.lineEditNoDeSerie_2.setObjectName("lineEditNoDeSerie_2")
        self.layoutChamps_2.addWidget(self.lineEditNoDeSerie_2)
        self.comboBoxSalle_2 = QtWidgets.QComboBox(ModificationEquipement)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.comboBoxSalle_2.setFont(font)
        self.comboBoxSalle_2.setMaxCount(2147483645)
        self.comboBoxSalle_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBoxSalle_2.setObjectName("comboBoxSalle_2")
        self.comboBoxSalle_2.addItem("")
        self.comboBoxSalle_2.addItem("")
        self.comboBoxSalle_2.addItem("")
        self.layoutChamps_2.addWidget(self.comboBoxSalle_2)
        self.comboBoxCentreDeService_2 = QtWidgets.QComboBox(ModificationEquipement)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.comboBoxCentreDeService_2.setFont(font)
        self.comboBoxCentreDeService_2.setMaxCount(2147483645)
        self.comboBoxCentreDeService_2.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.comboBoxCentreDeService_2.setObjectName("comboBoxCentreDeService_2")
        self.comboBoxCentreDeService_2.addItem("")
        self.comboBoxCentreDeService_2.addItem("")
        self.comboBoxCentreDeService_2.addItem("")
        self.layoutChamps_2.addWidget(self.comboBoxCentreDeService_2)
        self.dateEditDateDaquisition_2 = QtWidgets.QDateEdit(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEditDateDaquisition_2.setFont(font)
        self.dateEditDateDaquisition_2.setCalendarPopup(True)
        self.dateEditDateDaquisition_2.setObjectName("dateEditDateDaquisition_2")
        self.layoutChamps_2.addWidget(self.dateEditDateDaquisition_2)
        self.dateEditDateDuDernierEntretien_2 = QtWidgets.QDateEdit(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dateEditDateDuDernierEntretien_2.setFont(font)
        self.dateEditDateDuDernierEntretien_2.setCalendarPopup(True)
        self.dateEditDateDuDernierEntretien_2.setObjectName("dateEditDateDuDernierEntretien_2")
        self.layoutChamps_2.addWidget(self.dateEditDateDuDernierEntretien_2)
        self.comboBoxProvenance_2 = QtWidgets.QComboBox(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBoxProvenance_2.setFont(font)
        self.comboBoxProvenance_2.setObjectName("comboBoxProvenance_2")
        self.layoutChamps_2.addWidget(self.comboBoxProvenance_2)
        self.lineEditCodeASSET_2 = QtWidgets.QLineEdit(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEditCodeASSET_2.setFont(font)
        self.lineEditCodeASSET_2.setObjectName("lineEditCodeASSET_2")
        self.layoutChamps_2.addWidget(self.lineEditCodeASSET_2)
        self.verticalLayout.addLayout(self.layoutChamps_2)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.labelTitreCommentaires = QtWidgets.QLabel(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTitreCommentaires.setFont(font)
        self.labelTitreCommentaires.setObjectName("labelTitreCommentaires")
        self.horizontalLayout_3.addWidget(self.labelTitreCommentaires)
        self.textEditCommentaires = QtWidgets.QTextEdit(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.textEditCommentaires.setFont(font)
        self.textEditCommentaires.setObjectName("textEditCommentaires")
        self.horizontalLayout_3.addWidget(self.textEditCommentaires)
        self.gridLayout.addLayout(self.horizontalLayout_3, 3, 0, 1, 1)
        self.layoutTitre = QtWidgets.QHBoxLayout()
        self.layoutTitre.setObjectName("layoutTitre")
        self.label = QtWidgets.QLabel(ModificationEquipement)
        self.label.setStyleSheet("background: white;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("Images/add1.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.layoutTitre.addWidget(self.label)
        self.titreModificationEquipement = QtWidgets.QLabel(ModificationEquipement)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.titreModificationEquipement.setFont(font)
        self.titreModificationEquipement.setStyleSheet("background: white;")
        self.titreModificationEquipement.setObjectName("titreModificationEquipement")
        self.layoutTitre.addWidget(self.titreModificationEquipement)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layoutTitre.addItem(spacerItem)
        self.gridLayout.addLayout(self.layoutTitre, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(ModificationEquipement)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelTitreEtatDeService = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTitreEtatDeService.setFont(font)
        self.labelTitreEtatDeService.setStyleSheet("background: white;")
        self.labelTitreEtatDeService.setObjectName("labelTitreEtatDeService")
        self.horizontalLayout_4.addWidget(self.labelTitreEtatDeService)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButtonEnService = QtWidgets.QRadioButton(self.frame)
        self.radioButtonEnService.setObjectName("radioButtonEnService")
        self.verticalLayout_3.addWidget(self.radioButtonEnService)
        self.radioButtonEnMaintenance = QtWidgets.QRadioButton(self.frame)
        self.radioButtonEnMaintenance.setObjectName("radioButtonEnMaintenance")
        self.verticalLayout_3.addWidget(self.radioButtonEnMaintenance)
        self.radioButtonAuRebus = QtWidgets.QRadioButton(self.frame)
        self.radioButtonAuRebus.setObjectName("radioButtonAuRebus")
        self.verticalLayout_3.addWidget(self.radioButtonAuRebus)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(ModificationEquipement)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelTitreEtatDeConservation = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelTitreEtatDeConservation.setFont(font)
        self.labelTitreEtatDeConservation.setStyleSheet("background: white;")
        self.labelTitreEtatDeConservation.setObjectName("labelTitreEtatDeConservation")
        self.horizontalLayout_6.addWidget(self.labelTitreEtatDeConservation)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButtonQuasiNeuf = QtWidgets.QRadioButton(self.frame_2)
        self.radioButtonQuasiNeuf.setObjectName("radioButtonQuasiNeuf")
        self.verticalLayout_4.addWidget(self.radioButtonQuasiNeuf)
        self.radioButtonAcceptable = QtWidgets.QRadioButton(self.frame_2)
        self.radioButtonAcceptable.setObjectName("radioButtonAcceptable")
        self.verticalLayout_4.addWidget(self.radioButtonAcceptable)
        self.radioButtonEnFinDeVie = QtWidgets.QRadioButton(self.frame_2)
        self.radioButtonEnFinDeVie.setObjectName("radioButtonEnFinDeVie")
        self.verticalLayout_4.addWidget(self.radioButtonEnFinDeVie)
        self.radioButtonDesuet = QtWidgets.QRadioButton(self.frame_2)
        self.radioButtonDesuet.setObjectName("radioButtonDesuet")
        self.verticalLayout_4.addWidget(self.radioButtonDesuet)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem1)
        self.BoutonValider = QtWidgets.QPushButton(ModificationEquipement)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.BoutonValider.setFont(font)
        self.BoutonValider.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Images/check-symbol.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BoutonValider.setIcon(icon)
        self.BoutonValider.setObjectName("BoutonValider")
        self.horizontalLayout_8.addWidget(self.BoutonValider)
        self.BoutonModifier = QtWidgets.QPushButton(ModificationEquipement)
        self.BoutonModifier.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Images/Modify-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BoutonModifier.setIcon(icon1)
        self.BoutonModifier.setIconSize(QtCore.QSize(32, 32))
        self.BoutonModifier.setObjectName("BoutonModifier")
        self.horizontalLayout_8.addWidget(self.BoutonModifier)
        self.BoutonEnregistrer = QtWidgets.QPushButton(ModificationEquipement)
        self.BoutonEnregistrer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Images/save (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BoutonEnregistrer.setIcon(icon2)
        self.BoutonEnregistrer.setObjectName("BoutonEnregistrer")
        self.horizontalLayout_8.addWidget(self.BoutonEnregistrer)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem2)
        self.gridLayout.addLayout(self.horizontalLayout_8, 4, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 1, 1, 1, 1)

        self.retranslateUi(ModificationEquipement)
        QtCore.QMetaObject.connectSlotsByName(ModificationEquipement)

    def retranslateUi(self, ModificationEquipement):
        _translate = QtCore.QCoreApplication.translate
        ModificationEquipement.setWindowTitle(_translate("ModificationEquipement", "Form"))
        self.label_34.setText(_translate("ModificationEquipement", "ID : "))
        self.label_37.setText(_translate("ModificationEquipement", "Catégorie : "))
        self.label_36.setText(_translate("ModificationEquipement", "Marque : "))
        self.label_35.setText(_translate("ModificationEquipement", "Modèle : "))
        self.label_30.setText(_translate("ModificationEquipement", "No. de série : "))
        self.label_31.setText(_translate("ModificationEquipement", "Salle : "))
        self.label_33.setText(_translate("ModificationEquipement", "Centre de service : "))
        self.label_29.setText(_translate("ModificationEquipement", "Date d\'aquisition : "))
        self.label_27.setText(_translate("ModificationEquipement", "Date du dernier entretien : "))
        self.label_26.setText(_translate("ModificationEquipement", "Provenance : "))
        self.label_2.setText(_translate("ModificationEquipement", "Code ASSET :"))
        self.comboBoxCategorie_2.setItemText(0, _translate("ModificationEquipement", "Catégorie 1"))
        self.comboBoxCategorie_2.setItemText(1, _translate("ModificationEquipement", "Catégorie 2"))
        self.comboBoxCategorie_2.setItemText(2, _translate("ModificationEquipement", "Catégorie 3"))
        self.comboBoxSalle_2.setItemText(0, _translate("ModificationEquipement", "Salle 1"))
        self.comboBoxSalle_2.setItemText(1, _translate("ModificationEquipement", "Salle 2"))
        self.comboBoxSalle_2.setItemText(2, _translate("ModificationEquipement", "Salle 3"))
        self.comboBoxCentreDeService_2.setItemText(0, _translate("ModificationEquipement", "Centre de service X"))
        self.comboBoxCentreDeService_2.setItemText(1, _translate("ModificationEquipement", "Centre de service Y"))
        self.comboBoxCentreDeService_2.setItemText(2, _translate("ModificationEquipement", "Centre de service Z"))
        self.dateEditDateDaquisition_2.setDisplayFormat(_translate("ModificationEquipement", "dd-MM-yyyy"))
        self.dateEditDateDuDernierEntretien_2.setDisplayFormat(_translate("ModificationEquipement", "dd-MM-yyyy"))
        self.labelTitreCommentaires.setText(_translate("ModificationEquipement", "Commentaires : "))
        self.titreModificationEquipement.setText(_translate("ModificationEquipement", "Modification d\'équipement"))
        self.labelTitreEtatDeService.setText(_translate("ModificationEquipement", "État de service : "))
        self.radioButtonEnService.setText(_translate("ModificationEquipement", "En service"))
        self.radioButtonEnMaintenance.setText(_translate("ModificationEquipement", "En maintenance"))
        self.radioButtonAuRebus.setText(_translate("ModificationEquipement", "Au rebus"))
        self.labelTitreEtatDeConservation.setText(_translate("ModificationEquipement", "État de Conservation : "))
        self.radioButtonQuasiNeuf.setText(_translate("ModificationEquipement", "Quasi neuf"))
        self.radioButtonAcceptable.setText(_translate("ModificationEquipement", "Acceptable"))
        self.radioButtonEnFinDeVie.setText(_translate("ModificationEquipement", "En fin de vie"))
        self.radioButtonDesuet.setText(_translate("ModificationEquipement", "Désuet"))
        self.BoutonValider.setText(_translate("ModificationEquipement", "Valider"))
        self.BoutonModifier.setText(_translate("ModificationEquipement", "Modifier"))
        self.BoutonEnregistrer.setText(_translate("ModificationEquipement", "Enregistrer"))

