# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Req_Piece.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReqPiece(object):
    def setupUi(self, ReqPiece):
        ReqPiece.setObjectName("ReqPiece")
        ReqPiece.resize(797, 524)
        ReqPiece.setMinimumSize(QtCore.QSize(0, 0))
        ReqPiece.setMaximumSize(QtCore.QSize(1747, 16777126))
        ReqPiece.setStyleSheet("QWidget {\n"
"background:white;\n"
"}\n"
"\n"
"QPushButton {\n"
"padding: 1px;\n"
"border-style: solid;\n"
"border: 1px solid gray;\n"
"border-radius: 4px;\n"
"background: rgb(247,247,247);\n"
"}\n"
"\n"
"QPushButton::pressed {\n"
"padding: 1px;\n"
"color: black;\n"
"border-style: solid;\n"
"border: 1px solid gray;\n"
"border-radius: 8px;\n"
"background:rgb(169, 167, 170);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: qlineargradient(x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #edf2f8, stop: 1 #c8d9ea);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(ReqPiece)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_descriptiontitre = QtWidgets.QVBoxLayout()
        self.verticalLayout_descriptiontitre.setObjectName("verticalLayout_descriptiontitre")
        self.label_situationtitre = QtWidgets.QLabel(ReqPiece)
        self.label_situationtitre.setObjectName("label_situationtitre")
        self.verticalLayout_descriptiontitre.addWidget(self.label_situationtitre)
        self.label_interventiontitre = QtWidgets.QLabel(ReqPiece)
        self.label_interventiontitre.setObjectName("label_interventiontitre")
        self.verticalLayout_descriptiontitre.addWidget(self.label_interventiontitre)
        self.gridLayout.addLayout(self.verticalLayout_descriptiontitre, 7, 0, 2, 1)
        self.horizontalLayout_checkboxes = QtWidgets.QHBoxLayout()
        self.horizontalLayout_checkboxes.setObjectName("horizontalLayout_checkboxes")
        self.checkBox_savepdf = QtWidgets.QCheckBox(ReqPiece)
        self.checkBox_savepdf.setObjectName("checkBox_savepdf")
        self.horizontalLayout_checkboxes.addWidget(self.checkBox_savepdf)
        self.checkBox_courriel = QtWidgets.QCheckBox(ReqPiece)
        self.checkBox_courriel.setObjectName("checkBox_courriel")
        self.horizontalLayout_checkboxes.addWidget(self.checkBox_courriel)
        self.gridLayout.addLayout(self.horizontalLayout_checkboxes, 9, 1, 1, 2)
        self.verticalLayout_PieceTitreInfos = QtWidgets.QVBoxLayout()
        self.verticalLayout_PieceTitreInfos.setObjectName("verticalLayout_PieceTitreInfos")
        self.labelcategpiece_titre = QtWidgets.QLabel(ReqPiece)
        self.labelcategpiece_titre.setMaximumSize(QtCore.QSize(142, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelcategpiece_titre.setFont(font)
        self.labelcategpiece_titre.setObjectName("labelcategpiece_titre")
        self.verticalLayout_PieceTitreInfos.addWidget(self.labelcategpiece_titre)
        self.labelnompiece_titre = QtWidgets.QLabel(ReqPiece)
        self.labelnompiece_titre.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelnompiece_titre.setFont(font)
        self.labelnompiece_titre.setObjectName("labelnompiece_titre")
        self.verticalLayout_PieceTitreInfos.addWidget(self.labelnompiece_titre)
        self.labelnombrepiece_titre = QtWidgets.QLabel(ReqPiece)
        self.labelnombrepiece_titre.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelnombrepiece_titre.setFont(font)
        self.labelnombrepiece_titre.setObjectName("labelnombrepiece_titre")
        self.verticalLayout_PieceTitreInfos.addWidget(self.labelnombrepiece_titre)
        self.gridLayout.addLayout(self.verticalLayout_ReqPieceTitreInfos, 3, 2, 4, 1)
        self.verticalLayout_EquipTitreInfos = QtWidgets.QVBoxLayout()
        self.verticalLayout_EquipTitreInfos.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_EquipTitreInfos.setContentsMargins(-1, 0, 0, -1)
        self.verticalLayout_EquipTitreInfos.setSpacing(7)
        self.verticalLayout_EquipTitreInfos.setObjectName("verticalLayout_EquipTitreInfos")
        self.labeldate_titre = QtWidgets.QLabel(ReqPiece)
        self.labeldate_titre.setMaximumSize(QtCore.QSize(100, 16777213))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labeldate_titre.setFont(font)
        self.labeldate_titre.setObjectName("labeldate_titre")
        self.verticalLayout_EquipTitreInfos.addWidget(self.labeldate_titre)
        self.labelid_titre = QtWidgets.QLabel(ReqPiece)
        self.labelid_titre.setEnabled(True)
        self.labelid_titre.setMaximumSize(QtCore.QSize(100, 500))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelid_titre.setFont(font)
        self.labelid_titre.setObjectName("labelid_titre")
        self.verticalLayout_EquipTitreInfos.addWidget(self.labelid_titre)
        self.labelcateg_titre = QtWidgets.QLabel(ReqPiece)
        self.labelcateg_titre.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelcateg_titre.setFont(font)
        self.labelcateg_titre.setObjectName("labelcateg_titre")
        self.verticalLayout_EquipTitreInfos.addWidget(self.labelcateg_titre)
        self.labelmarque_titre = QtWidgets.QLabel(ReqPiece)
        self.labelmarque_titre.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelmarque_titre.setFont(font)
        self.labelmarque_titre.setObjectName("labelmarque_titre")
        self.verticalLayout_EquipTitreInfos.addWidget(self.labelmarque_titre)
        self.labelmodel_titre = QtWidgets.QLabel(ReqPiece)
        self.labelmodel_titre.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelmodel_titre.setFont(font)
        self.labelmodel_titre.setObjectName("labelmodel_titre")
        self.verticalLayout_EquipTitreInfos.addWidget(self.labelmodel_titre)
        self.labelsalle_titre = QtWidgets.QLabel(ReqPiece)
        self.labelsalle_titre.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelsalle_titre.setFont(font)
        self.labelsalle_titre.setObjectName("labelsalle_titre")
        self.verticalLayout_EquipTitreInfos.addWidget(self.labelsalle_titre)
        self.labelunite_titre = QtWidgets.QLabel(ReqPiece)
        self.labelunite_titre.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelunite_titre.setFont(font)
        self.labelunite_titre.setObjectName("labelunite_titre")
        self.verticalLayout_EquipTitreInfos.addWidget(self.labelunite_titre)
        self.labelnomtech_titre = QtWidgets.QLabel(ReqPiece)
        self.labelnomtech_titre.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.labelnomtech_titre.setFont(font)
        self.labelnomtech_titre.setObjectName("labelnomtech_titre")
        self.verticalLayout_EquipTitreInfos.addWidget(self.labelnomtech_titre)
        self.gridLayout.addLayout(self.verticalLayout_EquipTitreInfos, 3, 0, 4, 1)
        spacerItem = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 3, 1, 1)
        self.verticalLayout_Piecedata = QtWidgets.QVBoxLayout()
        self.verticalLayout_Piecedata.setObjectName("verticalLayout_Piecedata")
        self.labelcategpiece_data = QtWidgets.QLabel(ReqPiece)
        self.labelcategpiece_data.setMaximumSize(QtCore.QSize(100, 16777215))
        self.labelcategpiece_data.setText("")
        self.labelcategpiece_data.setObjectName("labelcategpiece_data")
        self.verticalLayout_Piecedata.addWidget(self.labelcategpiece_data)
        self.labelnompiece_data = QtWidgets.QLabel(ReqPiece)
        self.labelnompiece_data.setMaximumSize(QtCore.QSize(100, 16777215))
        self.labelnompiece_data.setText("")
        self.labelnompiece_data.setObjectName("labelnompiece_data")
        self.verticalLayout_Piecedata.addWidget(self.labelnompiece_data)
        self.labelnombrepiece_data = QtWidgets.QLabel(ReqPiece)
        self.labelnombrepiece_data.setMaximumSize(QtCore.QSize(100, 16777215))
        self.labelnombrepiece_data.setText("")
        self.labelnombrepiece_data.setObjectName("labelnombrepiece_data")
        self.verticalLayout_Piecedata.addWidget(self.labelnombrepiece_data)
        self.gridLayout.addLayout(self.verticalLayout_Piecedata, 3, 3, 4, 1)
        self.label_2 = QtWidgets.QLabel(ReqPiece)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.label_titreInfoEquip = QtWidgets.QLabel(ReqPiece)
        self.label_titreInfoEquip.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_titreInfoEquip.setFont(font)
        self.label_titreInfoEquip.setObjectName("label_titreInfoEquip")
        self.gridLayout.addWidget(self.label_titreInfoEquip, 1, 0, 1, 1)
        self.verticalLayout_Equipdata = QtWidgets.QVBoxLayout()
        self.verticalLayout_Equipdata.setObjectName("verticalLayout_Equipdata")
        self.labeldate_data = QtWidgets.QLabel(ReqPiece)
        self.labeldate_data.setText("")
        self.labeldate_data.setObjectName("labeldate_data")
        self.verticalLayout_Equipdata.addWidget(self.labeldate_data)
        self.labelid_data = QtWidgets.QLabel(ReqPiece)
        self.labelid_data.setText("")
        self.labelid_data.setObjectName("labelid_data")
        self.verticalLayout_Equipdata.addWidget(self.labelid_data)
        self.labelcateg_data = QtWidgets.QLabel(ReqPiece)
        self.labelcateg_data.setText("")
        self.labelcateg_data.setObjectName("labelcateg_data")
        self.verticalLayout_Equipdata.addWidget(self.labelcateg_data)
        self.labelmarque_data = QtWidgets.QLabel(ReqPiece)
        self.labelmarque_data.setText("")
        self.labelmarque_data.setObjectName("labelmarque_data")
        self.verticalLayout_Equipdata.addWidget(self.labelmarque_data)
        self.labelsalle_data = QtWidgets.QLabel(ReqPiece)
        self.labelsalle_data.setText("")
        self.labelsalle_data.setObjectName("labelsalle_data")
        self.verticalLayout_Equipdata.addWidget(self.labelsalle_data)
        self.labelunite_data = QtWidgets.QLabel(ReqPiece)
        self.labelunite_data.setText("")
        self.labelunite_data.setObjectName("labelunite_data")
        self.verticalLayout_Equipdata.addWidget(self.labelunite_data)
        self.labelnomtech_data = QtWidgets.QLabel(ReqPiece)
        self.labelnomtech_data.setText("")
        self.labelnomtech_data.setObjectName("labelnomtech_data")
        self.verticalLayout_Equipdata.addWidget(self.labelnomtech_data)
        self.gridLayout.addLayout(self.verticalLayout_Equipdata, 3, 1, 4, 1)
        self.titreLayout = QtWidgets.QHBoxLayout()
        self.titreLayout.setObjectName("titreLayout")
        self.labelTitreRequisitionPiece = QtWidgets.QLabel(ReqPiece)
        self.labelTitreRequisitionPiece.setMaximumSize(QtCore.QSize(250, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(18)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.labelTitreRequisitionPiece.setFont(font)
        self.labelTitreRequisitionPiece.setStyleSheet("background:white;")
        self.labelTitreRequisitionPiece.setObjectName("labelTitreRequisitionPiece")
        self.titreLayout.addWidget(self.labelTitreRequisitionPiece)
        spacerItem1 = QtWidgets.QSpacerItem(450, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.titreLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.titreLayout, 0, 0, 1, 4)
        self.verticalLayout_descriptiondata = QtWidgets.QVBoxLayout()
        self.verticalLayout_descriptiondata.setObjectName("verticalLayout_descriptiondata")
        self.label_situationdata = QtWidgets.QLabel(ReqPiece)
        self.label_situationdata.setText("")
        self.label_situationdata.setObjectName("label_situationdata")
        self.verticalLayout_descriptiondata.addWidget(self.label_situationdata)
        self.label_interventiondata = QtWidgets.QLabel(ReqPiece)
        self.label_interventiondata.setText("")
        self.label_interventiondata.setObjectName("label_interventiondata")
        self.verticalLayout_descriptiondata.addWidget(self.label_interventiondata)
        self.gridLayout.addLayout(self.verticalLayout_descriptiondata, 7, 1, 2, 3)
        spacerItem2 = QtWidgets.QSpacerItem(150, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 1, 1, 1)
        self.horizontalLayout_boutons = QtWidgets.QHBoxLayout()
        self.horizontalLayout_boutons.setObjectName("horizontalLayout_boutons")
        self.pushButton_annuler = QtWidgets.QPushButton(ReqPiece)
        self.pushButton_annuler.setMaximumSize(QtCore.QSize(16777215, 45))
        self.pushButton_annuler.setObjectName("pushButton_annuler")
        self.horizontalLayout_boutons.addWidget(self.pushButton_annuler)
        self.pushButton_valider = QtWidgets.QPushButton(ReqPiece)
        self.pushButton_valider.setMaximumSize(QtCore.QSize(16777215, 45))
        self.pushButton_valider.setObjectName("pushButton_valider")
        self.horizontalLayout_boutons.addWidget(self.pushButton_valider)
        self.gridLayout.addLayout(self.horizontalLayout_boutons, 10, 1, 1, 2)

        self.retranslateUi(ReqPiece)
        QtCore.QMetaObject.connectSlotsByName(ReqPiece)

    def retranslateUi(self, ReqPiece):
        _translate = QtCore.QCoreApplication.translate
        ReqPiece.setWindowTitle(_translate("Piece", "Form"))
        self.label_situationtitre.setText(_translate("ReqPiece", "Description de la situation :"))
        self.label_interventiontitre.setText(_translate("ReqPiece", "Description de l\'intervention :"))
        self.checkBox_savepdf.setText(_translate("ReqPiece", "Enregistrer en PDF"))
        self.checkBox_courriel.setText(_translate("ReqPiece", "Envoyer par courriel"))
        self.labelcategpiece_titre.setText(_translate("ReqPiece", "Catégorie de pièce :"))
        self.labelnompiece_titre.setText(_translate("ReqPiece", "Nom : "))
        self.labelnombrepiece_titre.setText(_translate("ReqPiece", "Nombre : "))
        self.labeldate_titre.setText(_translate("ReqPiece", "Date : "))
        self.labelid_titre.setText(_translate("ReqPiece", "ID : "))
        self.labelcateg_titre.setText(_translate("ReqPiece", "Catégorie : "))
        self.labelmarque_titre.setText(_translate("ReqPiece", "Marque : "))
        self.labelmodel_titre.setText(_translate("ReqPiece", "Modèle : "))
        self.labelsalle_titre.setText(_translate("ReqPiece", "Salle : "))
        self.labelunite_titre.setText(_translate("ReqPiece", "Unité : "))
        self.labelnomtech_titre.setText(_translate("ReqPiece", "Nom du technicien : "))
        self.label_2.setText(_translate("ReqPiece", "Pièce associée :"))
        self.label_titreInfoEquip.setText(_translate("ReqPiece", "Équipement: "))
        self.labelTitreRequisitionPiece.setText(_translate("ReqPiece", "Réquisition de pièce"))
        self.pushButton_annuler.setText(_translate("ReqPiece", "Valider"))
        self.pushButton_valider.setText(_translate("ReqPiece", "Annuler"))

